name: 组播源采集合并

on:
  schedule:
    - cron: '0 */6 * * *'  # 每六个小时的第 0 分钟运行
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests futures eventlet
          pip install opencv-python
          pip install beautifulsoup4
          pip install translate
          #pip install ffmpy
          pip install termcolor
          pip install func_timeout
          pip install replace
          pip install input
          pip install opencc
          pip install pypinyin
          pip install pytz 
          pip install tqdm

      - name: Run iptv
        run: python ${{ github.workspace }}/DXZB.py  # 更改为要运行的 py 文件

      - name: 提交更改
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .  # 暂存所有更改的文件
          git commit -m "Add generated files" || echo "没有需要提交的更改"  # 提交所有更改
          git push -f  # 强制推送
