name: zb

on:
  schedule:
    - cron: '0 */4 * * *'  # 每四个小时的第 0 分钟运行
  workflow_dispatch:
    分支:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install opencv-python requests
          # 添加其他需要的包
          
      - name: Run ZB
        run: python ${{ github.workspace }}/ZB.py

      - name: 提交更改
        run: |
          git config --local user.email "luoyexp@163.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
